name: Push Image from Azure Container Registry
description: push image from Azure Container Registry
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  simulator_image_docker_or_listofImages:
    description: 'User should input either a Docker image of the simulator or a list of images Ex:"simulator_simulator, asset_simulators ..."'
    required: true
    default: ''
  simulator_version_or_listofVersions:
    description: 'User should input either the version of the simulator or a list of versions Ex:"ASSET_v14.2.1, ASSET_v15.0.1 ..."'
    required: true
    default: ''
  platform_or_listofPlatforms:
    description: 'User should input either a single platform or a list of platforms to initialize Ex: "dev, perf, staging ...."'
    required: true
  tags_or_list_of_tags:
    description: 'User should input either a single tags or a list of tags Ex: "[ASSET_14.2.1], [ASSET_14.2.2], [ASSET_14.2.3]...."'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: push ACR simulator image
      run: |
        cd ${{ inputs.folder }}

        IFS=',' read -ra platforms_array <<< "${{ inputs.platform_or_listofPlatforms }}"
        IFS=',' read -ra list_of_images_simulator <<< "${{ inputs.simulator_image_docker_or_listofImages }}"
        IFS=',' read -ra list_of_version_simulator <<< "${{ inputs.simulator_version_or_listofVersions }}"
        IFS=',' read -ra list_of_tags <<< "${{ inputs.tags_or_list_of_tags }}"

        length_platforms=${#platforms_array[@]}
        length_list_images_simulator=${#list_of_images_simulator[@]}
        length_versions_simulator=${#list_of_version_simulator[@]}
        length_tags=${#list_of_tags[@]}

        if [ $length_platforms -eq 1 ] && [ $length_list_images_simulator -eq 1 ] && [ $length_versions_simulator -eq 1 ]; then
            babylon azure acr push -c ${{ env.CONTEXT_ID }} -p $platforms_array --image ${{ inputs.simulator_image_docker_or_listofImages }}:${{ inputs.simulator_version_or_listofVersions }}
        else
            index=0
            for platform in "${platforms_array[@]}"; do
                cleaned_platform=$(echo "$platform" | sed 's/ *//g')
                if [ "$cleaned_platform" != "${{ env.PLATFORM_ID }}" ]; then
                    docker images > ${PWD}/docker_images_logs.txt
                    LOG_FILE=${PWD}/docker_images_logs.txt
                    extract_repositories_and_tags() {
                        while IFS= read -r line; do
                            repository=$(echo "$line" | awk '{print $1}')
                            tag=$(echo "$line" | awk '{print $2}')
                            for image in "${list_of_images_simulator[@]}"; do
                                for verison in "${list_of_version_simulator[@]}"; do
                                    cleaned_image=$(echo "$image" | sed 's/ *//g')
                                    cleaned_version=$(echo "$verison" | sed 's/ *//g')
                                    if [ "$repository:$tag" == "$cleaned_image:$cleaned_version" ]; then
                                        babylon azure acr pull -c ${{ env.CONTEXT_ID }} -p $cleaned_platform --image $cleaned_image:$cleaned_version
                                        index=$((index + 1))
                                    fi
                                done
                            done
                        done < "$LOG_FILE"
                    }
                    extract_repositories_and_tags
                fi
            done
        fi
      shell: bash