name: Pull Image from Azure Container Registry
description: Pull image from Azure Container Registry
inputs:
  folder:
    description: 'Working-dir folder'
    required: true
    default: 'personal'
  simulator_image_docker_dev:
    description: 'simulator_image_docker_dev'
    required: true
    default: ''
  simulator_version_dev:
    description: 'simulator_version_dev'
    required: true
    default: ''
  simulator_image_docker_pef:
    description: 'simulator_image_docker_perf'
    required: true
    default: ''
  simulator_version_perf:
    description: 'simulator_version_perf'
    required: true
    default: ''
  simulator_image_docker_staging:
    description: 'simulator_image_docker_staging'
    required: true
    default: ''
  simulator_version_staging:
    description: 'simulator_version_staging'
    required: true
    default: ''
  platforms:
    description: 'List of platforms to initialize'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pull ACR simulator image
      run: |
        cd ${{ inputs.folder }}
        IFS=',' read -ra platforms_array <<< "${{ inputs.platforms }}"
        for platform in "${platforms_array[@]}"; do
          if [ "$platform" != "${{ env.PLATFORM_ID }}" ]; then 
            if [ "$platform" == "perf" ]; then 
              docker tag ${{ inputs.simulator_image_docker_perf }}:${{ inputs.simulator_version_perf }} ${{ inputs.simulator_image_docker_perf }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
              babylon azure acr push -c ${{ env.CONTEXT_ID }} -p $platform --image ${{ inputs.simulator_image_docker_perf }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
            elif [ "$platform" == "staging " ]; then 
              docker tag ${{ inputs.simulator_image_docker_staging }}:${{ inputs.simulator_version_staging }} ${{ inputs.simulator_image_docker_staging }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
              babylon azure acr push -c ${{ env.CONTEXT_ID }} -p $platform --image ${{ inputs.simulator_image_docker_staging }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
            elif [ "$platform" == "dev" ]; then
              docker tag ${{ inputs.simulator_image_docker_dev}}:${{ inputs.simulator_version_dev }} ${{ inputs.simulator_image_docker_staging }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
              babylon azure acr push -c ${{ env.CONTEXT_ID }} -p $platform --image ${{ inputs.simulator_image_docker_dev }}:ASSET_14_$(date +"%Y-%m-%d-%Hh%M")_$platformZ
            fi
          fi
        done
      shell: bash
