name: Push Image to Azure Container Registry
description: Push image to Azure Container Registry
inputs:
  platform_or_list_of_Platforms:
    description: 'User should input either a single platform or a list of platforms to initialize Ex: "dev, perf, staging ...."'
    required: true
    default: ''
  simulator_image_docker_or_list_of_Images:
    description: 'User should input either a Docker image of the simulator or a list of images Ex:"simulator_simulator, asset_simulators ..."'
    required: true
    default: ''
  tag_or_list_of_tags:
    description: 'User should input either a single tags or a list of tags Ex: "[ASSET_14.2.1], [ASSET_14.2.2], [ASSET_14.2.3]...."'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Push to ACR simulator image
      run: |
        IFS=',' read -ra platforms_array <<< "${{ inputs.platform_or_list_of_Platforms }}"
        IFS=',' read -ra list_of_images_simulator <<< "${{ inputs.simulator_image_docker_or_list_of_Images }}"
        IFS=',' read -ra list_of_tags <<< "${{ inputs.tag_or_list_of_tags }}"

        length_platforms=${#platforms_array[@]}
        length_list_images_simulator=${#list_of_images_simulator[@]}
        length_tags=${#list_of_tags[@]}

        if [ $length_platforms -eq 1 ] && [ $length_list_images_simulator -eq 1 ] && [ $length_tags -eq 1 ]; then
                echo "Push images_simulator: $list_of_images_simulator:$list_of_tags in platform : $platforms_array"
        else
            for platform in "${platforms_array[@]}"; do
                cleaned_platform=$(echo "$platform" | sed 's/ *//g')
                if [ "$cleaned_platform" != "${{ env.PLATFORM_ID }}" ]; then
                    docker images > ${PWD}/docker_images_logs.txt
                    LOG_FILE=${PWD}/docker_images_logs.txt
                    extract_repositories_and_tags() {
                        while IFS= read -r line; do
                            repository=$(echo "$line" | awk '{print $1}')
                            tag=$(echo "$line" | awk '{print $2}')
                            for image in "${list_of_images_simulator[@]}"; do
                                for verison in "${list_of_tags[@]}"; do
                                    cleaned_image=$(echo "$image" | sed 's/ *//g')
                                    cleaned_version=$(echo "$verison" | sed 's/ *//g')
                                    if [ "$repository:$tag" == "$cleaned_image:$cleaned_version" ]; then
                                        echo "Push images_taged: --> $repository:$tag in plaftorm $cleaned_platform"
                                    fi
                                done
                            done
                        done < "$LOG_FILE"
                    }
                    extract_repositories_and_tags
                fi
            done
        fi
      shell: bash


      